<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<?php 
$host = $_SERVER['HTTP_HOST'];
$static = ($host == 'dev.tomdoggett.net' ? 'dev.static.tomdoggett.net' : 'static.tomdoggett.net');
$tweet = json_decode(file_get_contents('http://api.twitter.com/1/statuses/user_timeline.json?screen_name=NoCoolName_Tom&count=1'))[0];
$created_at = new DateTime($tweet->created_at);
$interval = $created_at->diff(new DateTime());
$diff = array();
if ($interval->format('%y')) {
	$diff[] = $interval->format('%y years');
}
if ($interval->format('%m')) {
	$diff[] = $interval->format('%m months');
}
if ($interval->format('%d')) {
	$diff[] = $interval->format('%d days');
}
if (count($diff) == 0 && $interval->format('%h')) {
	$diff[] = $interval->format('%h hours');
}
if (count($diff) == 0 && $interval->format('%i')) {
	$diff[] = $interval->format('%i minutes');
}
$diff = implode(', ', $diff) . ' ago';
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<title>Tom Doggett</title>
		<link rel="stylesheet" type="text/css" href="//<?=$static?>/css/style-blue.css">
		<!--[if IE 7]>
			<link rel="stylesheet" type="text/css" href="//static.tomdoggett.net/css/ie7.css" media=screen>
		<![endif]-->
		<script type="text/javascript" src="//<?=$static?>/js/jquery.min.js"></script>
		<script type="text/javascript" src="//<?=$static?>/js/cufon-yui.js"></script>
		<script type="text/javascript" src="//<?=$static?>/js/Harabara_700.font.js"></script>
		
		<!-- Cufon font replacement -->
		<script type="text/javascript">
			Cufon.replace('ul#navigation li span', { textShadow: '0 2px rgba(0, 0, 0, 0.2)' });
		</script>
		<script type="text/javascript">
			Cufon.replace('#social ul li a', {hover:true});
		</script>
		
		<!-- Navigation and Content sliding effects -->
		<script type="text/javascript">
			$(document).ready(function(){
				$('#navigation span.about').css('opacity','0.6');
				$('ul#navigation li').hover(function(){
					$(this).stop().animate({marginRight:6}, 250);
					}, function(){
						$(this).stop().animate({marginRight:0}, 250)
				});
				$('#navigation span.about').click(function(e){
					$('#content').animate({'top':'0'},700);
					$('#navigation a').css('opacity','1');
					$(this).css('opacity','0.6');
				});
				$('#navigation span.work').click(function(e){
					$('#content').animate({'top':'-560'},700);
					$('#navigation a').css('opacity','1');
					$(this).css('opacity','0.6');
				});
				$('#navigation span.social').click(function(e){
					$('#content').animate({'top':'-1120'},700);
					$('#navigation a').css('opacity','1');
					$(this).css('opacity','0.6');
				});
				$('#navigation span.contact').click(function(e){
					$('#content').animate({'top':'-1680'},700);
					$('#navigation a').css('opacity','1');
					$(this).css('opacity','0.6');
				});
			});
		</script>
	</head>
	<body>
		<div id="pagewrap">
			
			<!-- Site navigation -->
			<div id="left">
				<ul id="navigation">
					<li><span class="about">about me</span></li>
					<li><span class="work">my skills</span></li>
					<li><span class="social">my social</span></li>
					<li><span class="contact">contact me</span></li>
				</ul>
			</div>
			
			<!-- Site content -->
			<div id="right">
				<div id="container">
					<ul id="content">
						<li id="about" class="content-block">
							<img src="//<?=$static?>/images/photo.jpg" alt="photo">
							<h2 class="name"><small>Hi! I'm</small>Tom Doggett</h2>
							<p>I am a programmer: I enjoy web and Linux programming in particular.  I enjoy learning and a good challenge: this is what has led me to enjoy learning and using such things as <img src="http://s.wordpress.com/latex.php?latex=\LaTeX&bg=transparent&fg=111111&s=0" class="latexlogo" alt="LaTeX"/>, AWS, vim, and even Haskell. I try to always keep on top of new skills that will teach me good habits, such as unit testing and trying to correctly use various design patterns; I've presented on numerous topics at the Utah Open Source Conference including Amazon Web Services, Tropo telephony integration, the git-flow model, PHP code analysis tools, and Jenkins Continuous Integration Server.  I get a thrill from finding clever and concise solutions to tricky problems.  Programming aside, I'm a nice guy who enjoys having fun with varied activities like biking, writing, ancient languages, and video games.</p>
							<h3>My best skills:</h3>
							<ul>
								<li>PHP</li>
								<li>symfony Framework (1.x)</li>
								<li>Linux</li>
							</ul>
						</li>
						<li id="work" class="content-block">
							<p></p>
							<h3>Open Source Projects:</h3>
							<ul>
								<li class="project"><h4>Creator and Lead for OpenMicNight</h4><p class="projectlink emph">Podcast Scheduler and Organizer for Subreddit Communities</p><p class="projectlink marginbottom"><a href="https://github.com/nocoolnametom/OpenMicNight" target="_blank">https://github.com/nocoolnametom/OpenMicNight</a></p></li>
							</ul>
							<h3>Certifications:</h3>
							<ul>
								<li class="project"><h4>Zend Certified Engineer PHP5</h4><p class="projectlink emph">PHP programming and Development</p><p class="projectlink">Aug 2009 - <a href="http://www.zend.com/en/yellow-pages#show-ClientCandidateID=ZEND011727" target="_blank">ZEND011727</a></p></li>
								<li class="project"><h4>Oracle Certified Associate MySQL 5.5</h4><p class="projectlink marginbottom">Aug 2010</a></li>
							</ul>
							<h3>Skills:</h3>
							<ul>
								<li class="project"><p class="projectlink"><span class="listleader">Best</span>  PHP, symfony Framework (1.x), jQuery, Linux</p></li>
								<li class="project"><p class="projectlink"><span class="listleader">Better</span> Office Tools (MS and Libre), Javascript/jQuery, Regular Expressions, <img src="http://s.wordpress.com/latex.php?latex=\LaTeX&bg=transparent&fg=000000&s=0" class="latexlogo" alt="LaTeX"/>, MySQL/MariaDB, Apache, Zend Framework, PHPUnit, Tropo, git, gitflow, Doctrine, vim, AWS, Jenkins/Hudson, RESTful architecture</p></li>
								<li class="project"><p class="projectlink"><span class="listleader">Good</span> Bash Scripting, C++, C#, nUnit, Java, Ruby, HTML5, cURL, CouchDB, python, CoffeeScript, django, Symfony Framework 2, Gearman</p></li>
							</ul>
						</li>
						<li id="social">
							<div id="tweet">
								<p class="tweet-text"><?=$tweet->text;?></p>
								<p class="tweet-meta">- <?=$diff;?> on <a href="https://twitter.com/NoCoolName_Tom">Twitter</a></p>
							</div>
							<ul>
								<li class="gplus"><a href="https://plus.google.com/101615050717338574454" target="_blank">google plus</a></li>
								<li class="stackoverflow"><a href="http://careers.stackoverflow.com/nocoolnametom" target="_blank">stackoverflow</a></li>
								<li class="linkedin"><a href="https://www.linkedin.com/pub/thomas-doggett/8/882/973" target="_blank">linked-in</a></li>
								<li class="github"><a href="https://github.com/nocoolnametom/" target="_blank">github</a></li>
								<li class="blogger"><a href="http://blog.tomdoggett.net/" target="_blank">blogger</a></li>
							</ul>
						</li>
						<li id="contact">
							<p>Feel free to get in touch with me about anything!  I'm always happy to help.</p>
							<h3>Drop me a note</h3>
							<form>
								<ul>
									<li class="msgname"><label>Name: </label><input type="text" name="name"></li>
									<li><label>E-mail: </label><input type="text" name="email"></li>
									<li><label>Message: </label><textarea name="message" rows=4 cols=35></textarea></li>
									<li><input class="send" type="submit" value="Send"></li>
								</ul>
							</form>
							<div id="contactinfo">
								<h3>Contact Information</h3>
								<p>2182 Toronto Ln, Concord, CA 94520</p>
								<p class="phone">925-421-0019</p>
								<p class="email">nocoolnametom@gmail.com</p>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</body>
</html>
